# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 20
# fn_single_line = true
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
hard_tabs = false
# hex_literal_case = "Lower"
# imports_granularity = "Module"
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 50
match_block_trailing_comma = true
max_width = 96
merge_derives = true
newline_style = "Unix"
# normalize_comments = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# struct_field_align_threshold = 20
# struct_lit_single_line = true
tab_spaces = 4
# trailing_comma = "Vertical"
# trailing_semicolon = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
# where_single_line = true
# wrap_comments = true
