[package]
  name = "princemuel-vercel-api"
  version = "0.1.0"
  edition = "2021"
  publish = false

[dependencies]
  tokio = { version = "1", features = ["macros"] }
  serde = { version = "1", features = ["derive"] }
  serde_json = { version = "1", features = ["raw_value"] }
  serde_derive = "1"
  vercel_runtime = { version = "1" }
  dotenv = "0.15.0"
  octocrab = "0.38.0"
  uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }

[lib]
  path = "src/lib.rs"

[[bin]]
  name = "hello"
  path = "api/hello.json.rs"
