## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://ntl.fyi/file-based-build-config

[build]
  command = "npm run build"
  # edge_functions = "netlify/edge-functions"
  # functions      = "netlify/functions"
  ignore  = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
  publish = "dist"

[[redirects]]
  force  = true                         # ensure to always redirect
  from   = "/api/*"                     # simplify all calls to serverless functions
  status = 200                          # ok code
  to     = "/.netlify/functions/:splat" # all function calls will go to this path

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    CDN-Cache-Control         = "public, durable, s-maxage=18000, stale-while-revalidate=604800, stale-if-error=604800, immutable"
    Cache-Control             = "public, max-age=3600, must-revalidate"
    Netlify-CDN-Cache-Control = "public, durable, s-maxage=18000, stale-while-revalidate=604800, stale-if-error=604800, immutable"
    Strict-Transport-Security = "max-age=31536000"
    X-Content-Type-Options    = "nosniff"
    X-Frame-Options           = "DENY"
    X-XSS-Protection          = "1; mode=block"
